### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by ikoamu** [ikoamu/publish-org-roam-ui#4]
search for nodes based on their titles or contents

**Comment by Thysrael** [comment]
Wow，that so cool!

**Comment by Thysrael** [comment]
Congrats on finishing the feature, I tried it out and it works great, so cool.
Also I would like to ask about being able to have the focus fixed on the results of a search: when I search for a node, it works as if I clicked on that node.
I noticed that you added this feature yourself and it's not an upstream feature. That's why I brought the issue to your attention. Just ignore me if something doesn't fit.
Apologies for the intrusion.

Translated with DeepL.com (free version)

**Comment by Thysrael** [comment]
Is there any way to move the search results node to the center of the screen or make him blink a bit.
This would have the advantage of quickly locating the search node in the Org-Roam-UI, making it easy to further view other nodes that are linked to it.
